name: Deploy to AWS

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/create_reservation_microservice_image:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/create_reservation_microservice_image:latest

      - name: Conectar a AWS EC2 y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_M }}
          username: ${{ secrets.EC2_USER_M }}
          key: ${{ secrets.EC2_SSH_KEY_M }}
          script: |
            echo "🚀 Iniciando despliegue en AWS EC2..."

            # Detener y eliminar el contenedor si ya existe
            if sudo docker ps -a --format '{{.Names}}' | grep -q create_reservation_microservice_container; then
              echo "🛑 Deteniendo y eliminando contenedor existente..."
              sudo docker stop create_reservation_microservice_container
              sudo docker rm create_reservation_microservice_container
            fi

            # Remover imágenes antiguas para evitar acumulación
            echo "🧹 Limpiando imágenes antiguas..."
            sudo docker image prune -af || true

            # Descargar la última versión de la imagen desde Docker Hub
            echo "📥 Descargando nueva imagen..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/create_reservation_microservice_image:latest

            # Ejecutar el nuevo contenedor con las variables de entorno
            echo "🚀 Ejecutando nuevo contenedor..."
            sudo docker run -d --name create_reservation_microservice_container \
              --env PORT=${{ secrets.PORT }} \
              --env DB_PARKINGLOTS_HOST=${{ secrets.DB_PARKINGLOTS_HOST }} \
              --env DB_PARKINGLOTS_USER=${{ secrets.DB_PARKINGLOTS_USER }} \
              --env DB_PARKINGLOTS_PASSWORD=${{ secrets.DB_PARKINGLOTS_PASSWORD }} \
              --env DB_PARKINGLOTS_NAME=${{ secrets.DB_PARKINGLOTS_NAME }} \
              --env DB_RESERVATIONS_HOST=${{ secrets.DB_RESERVATIONS_HOST }} \
              --env DB_RESERVATIONS_USER=${{ secrets.DB_RESERVATIONS_USER }} \
              --env DB_RESERVATIONS_PASSWORD=${{ secrets.DB_RESERVATIONS_PASSWORD }} \
              --env DB_RESERVATIONS_NAME=${{ secrets.DB_RESERVATIONS_NAME }} \
              --env VEHICLE_SERVICE_URL=${{ secrets.VEHICLE_SERVICE_URL }} \
              --env PARKINGLOT_SERVICE_CAPACITY_URL=${{ secrets.PARKINGLOT_SERVICE_CAPACITY_URL }} \
              --env PARKINGLOT_SERVICE_URL=${{ secrets.PARKINGLOT_SERVICE_URL }} \
              --env PARKINGLOT_SERVICE_DISMINUYE_URL=${{ secrets.PARKINGLOT_SERVICE_DISMINUYE_URL }} \
              -p 4000:4000 \
              ${{ secrets.DOCKER_USERNAME }}/create_reservation_microservice_image:latest

            echo "✅ Despliegue completado con éxito."
